name: Build and push Metadata service for dev cluster
on: ["workflow_dispatch"]

jobs:
  deploy-codium-development:
    runs-on: [ubuntu-latest]

    permissions:
        contents: 'write'
        id-token: 'write'

    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - id: dockerx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/430654255805/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: github-actions@codium-development.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: development-cluster
          location: us-central1

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build push and install
        run: |
          tagname="us-central1-docker.pkg.dev/codium-development/codium-repo/metadata-service:build-${GITHUB_RUN_NUMBER}"
          docker build -t $tagname .
          docker push $tagname
          helm upgrade --create-namespace --install metadata-service helm -n metadata-service --set image=$tagname
