name: Build and push metadata-service for intuit
on: ["workflow_dispatch"]

jobs:
  deploy-codium-development:
    runs-on: [ubuntu-latest]

    permissions:
        contents: 'write'
        id-token: 'write'

    steps:
      - name : Checkouts
        uses: actions/checkout@v2

      - id: dockerx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Intuit Azure container registry
        uses: docker/login-action@v3
        with:
          registry: intuitpragent.azurecr.io
          username: ${{ secrets.INTUIT_ACR_USERNAME }}
          password: ${{ secrets.INTUIT_ACR_PASSWORD }}

      - name: Set short commit SHA and app version as environment variables
        run: | 
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "APP_VERSION="${GITHUB_RUN_NUMBER}_${{ env.SHORT_SHA }}" >> $GITHUB_ENV

      - name: Build push
        run: |
          tagname="intuitpragent.azurecr.io/metadata-service:${{ env.APP_VERSION }}"
          tagname_latest="intuitpragent.azurecr.io/metadata-service:latest"
          echo $tagname
          docker build --build-arg APP_VERSION=${{ env.APP_VERSION }} -t $tagname .
          docker tag $tagname $tagname_latest
          docker push $tagname
          docker push $tagname_latest
          # update values file with image number
          sed -i "s|image: .*|image: $tagname|g" helm/values.yaml
          sed -i "s|use_external_secrets: .*|use_external_secrets: false|g" helm/values.yaml

      - name: Create helm chart zip
        run: |
          zip -r metadata-service-helm.zip helm
          echo "metadata-service-helm.zip created"

      - name: Upload helm chart zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: metadata-service-helm
          path: metadata-service-helm.zip


